Changes for migration to be postgres to be merged to main
Code4GovTech/discord-bot pull request #86
Opened 2024-11-14 07:27 UTC by jaanbaaz

2024-11-14 07:57 UTC, karntrehan requested changes

2024-11-14 07:57 UTC, karntrehan commented on cogs/discordDataScraper.py
> +        # contributor = PostgresClient().read(
Lets delete the commented code.

2024-11-14 07:57 UTC, karntrehan commented on cogs/badges.py
> +        discordMemberData = PostgresClient().read(
Can we create 1 class level instance of postgresclient please? Creating a new one each time seems unncessary.

2024-11-14 07:57 UTC, karntrehan commented on cogs/badges.py
> +                "merged": PostgresClient(table="connected_prs").read(
This seems to be a different syntax. We should have a uniform syntax across the board.

2024-11-14 07:57 UTC, karntrehan commented on cogs/listeners/role_events_cog.py
> +            PostgresClient().addChapter(roleId=role.id, orgName=orgName, type="COLLEGE")
Class level instance here as well. Lets do it for all classes.

2024-11-14 07:57 UTC, karntrehan commented on cogs/userInteractions.py
> +    @tasks.loop(minutes=10)
Seems to be a duplicate? Merging issue?

2024-11-15 09:18 UTC, karntrehan approved these changes

2025-01-10 09:59 UTC, Shreyash-work-em commented
Updated pull request added

2025-01-10 09:59 UTC, closed without merging